server:
  port: 8085
  
  
  
logging:
  type: json
  application:
    name: Polycruz
  
reservoir:
  trendingMintsUrl: "https://api.reservoir.tools/collections/trending-mints/v2"
  askCancelUrl: "https://api.reservoir.tools/tokens/{token}/activity/v5"
      