server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    key-alias: selfsigned
  
  
  
logging:
  config: classpath:logback-spring.xml
  level:
    com.polycruz: DEBUG
  type: json
  application:
    name: Polycruz

reservoir:
  apiKey: "2fb57ee0-63ec-53bb-9311-5a0cc6b8bc49"
  trendingMintsUrl: "/collections/trending-mints/v2"
  collectionsV7Url: "/collections/v7"
  tokens: "/tokens/v7"
  activityUrl: "/tokens/0x5af0d9827e0c53e4799bb226655a1de152a425a5:9099/activity/v5"
  askCancelUrl: "/tokens/0x5af0d9827e0c53e4799bb226655a1de152a425a5:9099/activity/v5"
  salesUrl: "/sales/v6"
  trendingApi: "/collections/trending/v1?period={period}&sortBy={sortBy}"
  trendingMints: "/collections/trending-mints/v2?period={period}&limit={limit}&sortDirection={sortDirection}&offset={offset}"
  topSales: "/sales/v6?startTimestamp={startTimestamp}&sortBy={sortBy}&sortDirection={sortDirection}&limit={limit}&offset={offset}&includeTokenMetadata={includeTokenMetadata}"
  tokenDetailUrl: "/api/unleash/nft/1/0x5af0d9827e0c53e4799bb226655a1de152a425a5/9099"
  statsUrl: "/chain/stats/v1"
  collectionActivity: "/collections/activity/v6"
  collectionSearch: "/collections/search/v1"
  topTrader: "/collections/0xbd3531da5cf5857e7cfaa92426877b022e612cf8/top-traders/v1"
  aiValuationonLoad: "/api/unleash/collection/1/0xbd3531da5cf5857e7cfaa92426877b022e612cf8"
  tokenActivityUrl: "https://api.reservoir.tools/tokens/{contract}:{tokenId}/activity/v5"
  attributes: "https://api.reservoir.tools/collections/0xbd3531da5cf5857e7cfaa92426877b022e612cf8/attributes/explore/v6"


  

spring:
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      adjust-dates-to-context-time-zone: false


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


  
      
